<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.0">
  <POU Name="ClamperFilterSide" Id="{4cfbb8e7-dd19-45d2-8e96-6129406da078}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ClamperFilterSide EXTENDS RunUnitSlave
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="ClamperFilterSide">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>