<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.0">
  <POU Name="ClamperSnapSide" Id="{c14fe538-a423-480e-b144-3ced6a766222}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ClamperSnapSide EXTENDS RunUnitSlave
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="ClamperSnapSide">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>