<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.0">
  <POU Name="RunCoordinator" Id="{93db79ea-7610-40ae-89e3-5adae225f547}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK RunCoordinator EXTENDS RunGroupNode
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[SUPER^();

CASE outputState OF 
	//------------Initialize
	eSpecialStates.GENERIC_GROUP_IDLE:
		//-----------------
		//	IDLE: wait command
		//-----------------
	//------------------------Working
	16#20:
		//------------------
		//	Engineering mode
		//------------------
	16#30:
		//------------------
		//	Daily check mode
		//	1. Bypass some stations
		//  2. Prompt meesage/door interlock
		//  3. Execute SCARA DAILY CHECK
		//------------------
	16#50:
		//---------------------------
		//	Production mode
		//  1. Execute SCARA ASSEMBLE
		//---------------------------
	16#FF:
		//--------------------------------
		//Emergency stop
		// 1. No way out except initialize
		//--------------------------------
END_CASE]]></ST>
    </Implementation>
    <LineIds Name="RunCoordinator">
      <LineId Id="13" Count="4" />
      <LineId Id="104" Count="1" />
      <LineId Id="103" Count="0" />
      <LineId Id="27" Count="0" />
      <LineId Id="82" Count="3" />
      <LineId Id="40" Count="0" />
      <LineId Id="96" Count="1" />
      <LineId Id="106" Count="1" />
      <LineId Id="109" Count="0" />
      <LineId Id="95" Count="0" />
      <LineId Id="42" Count="0" />
      <LineId Id="93" Count="1" />
      <LineId Id="108" Count="0" />
      <LineId Id="77" Count="0" />
      <LineId Id="98" Count="2" />
      <LineId Id="110" Count="0" />
      <LineId Id="101" Count="0" />
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>