<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.0">
  <POU Name="RunScaraAgent" Id="{1f4adf83-c440-4f87-8ce9-122caf9d3620}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK RunScaraAgent EXTENDS RunUnitGeneric
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR	
	
//	outputs AT%Q* : ARRAY[0..3] OF BOOL; //TODO ,vacuum break
	//-------------------
	// Remote control
	//-------------------
	start AT %Q* : BOOL;
	stop AT%Q* :BOOL;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
//control handshaking signal to slaveworkingSignal
//mission:
//2. sequence start/stop


]]></ST>
    </Implementation>
    <LineIds Name="RunScaraAgent">
      <LineId Id="335" Count="2" />
      <LineId Id="339" Count="0" />
      <LineId Id="341" Count="0" />
      <LineId Id="387" Count="0" />
      <LineId Id="238" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>