<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.0">
  <POU Name="RunSensor" Id="{907b1e5f-f536-4a97-8bfe-6b708c2c8f23}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK RunSensor
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	sensor : POINTER TO RunSignal;
	debounceOn AT%Q* : BOOL;
	debounceOff AT%Q* : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[IF sensor <> 0 THEN
	//debounceOn
END_IF]]></ST>
    </Implementation>
    <LineIds Name="RunSensor">
      <LineId Id="9" Count="0" />
      <LineId Id="13" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>