<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="POU" Id="{d4f306c9-0791-47f5-8302-b27a52036216}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION POU : BOOL
VAR_INPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="POU">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>