<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="TEST_CYLINDER" Id="{9ae041d2-c241-42ec-9562-72f082a519e8}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM TEST_CYLINDER
VAR
	cylBlock : CylinderBlockBase;
	state : INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="TEST_CYLINDER">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>