<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.10">
  <POU Name="RunETest" Id="{72e72744-8d8b-4127-a1f7-17ac70d49060}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK RunETest EXTENDS RunAxisInspection
VAR
	//Cylinders
	connectorHolder : RunCylinder;
	cableHolder : RunCylinder;
	plugin : RunCylinder;
	//Sensors
	tongueExistedA : RunSignal;
	tongueExistedB : RunSignal;
	tongueGlueA : RunSignal;
	tongueGlueB : RunSignal;
	//from tester
	cableAttached AT%I* : BOOL;
	cableGrade AT%I* : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Initialize" Id="{b1cb528c-756c-4543-b261-8a9a85e25c02}">
      <Declaration><![CDATA[METHOD Initialize : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[SUPER^();]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="RunETest">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="RunETest.Initialize">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>