<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.10">
  <POU Name="RunETest" Id="{72e72744-8d8b-4127-a1f7-17ac70d49060}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK RunETest EXTENDS RunAxisInspection
VAR
	//Cylinders
	connectorHolder : RunCylinder;
	cableHolder : RunCylinder;
	plugin : RunCylinder;
	//Sensors
	tongueExistedA : RunSignal;
	tongueExistedB : RunSignal;
	tongueGlueA : RunSignal;
	tongueGlueB : RunSignal;
	//from tester
	cableAttached AT%I* : BOOL;
	cableGrade AT%I* : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="RunETest">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>