<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.10">
  <POU Name="base" Id="{4bdf7bb1-2c95-4efa-aeb8-c2bd9c7d66fd}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK base 
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	field1 : INT := 555;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="METH" Id="{3ea16346-5c9b-4274-a1db-2e36b12f445a}">
      <Declaration><![CDATA[METHOD METH : STRING
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[METH := 'base';]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="base">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="base.METH">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>