<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.10">
  <POU Name="derived1" Id="{3a957143-d7e5-4c53-995e-192f1163385e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK derived1 EXTENDS base implements itf
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="ITF_METH" Id="{7d04ef0c-c37a-4622-9de2-7e0beaac75fe}">
      <Declaration><![CDATA[METHOD ITF_METH : STRING
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[ITF_METH := 'derived1 itf method';]]></ST>
      </Implementation>
    </Method>
    <Method Name="METH" Id="{6e1e2dac-51f8-47fe-87c4-47921436fec7}">
      <Declaration><![CDATA[METHOD METH : STRING
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[METH := 'derived1';]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="derived1">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="derived1.ITF_METH">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="derived1.METH">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>