<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.10">
  <POU Name="derived2" Id="{97ebf8f7-b506-4f0c-841b-341e4c343500}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK derived2 EXTENDS base implements itf
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="ITF_METH" Id="{0ed03664-ab68-49eb-ab7a-5edb4057c1d9}">
      <Declaration><![CDATA[METHOD ITF_METH : STRING
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[ITF_METH := 'derived2 itf method';]]></ST>
      </Implementation>
    </Method>
    <Method Name="METH" Id="{c2704ac9-6f41-43a1-83e2-29aada0b9573}">
      <Declaration><![CDATA[METHOD METH : string
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[METH := 'derived2';]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="derived2">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="derived2.ITF_METH">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="derived2.METH">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>