<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.10">
  <POU Name="ParametersHome" Id="{1ec44c4d-06f6-4832-b786-9152cf1735f2}" SpecialFunc="None">
    <Declaration><![CDATA[TYPE ParametersHome :
STRUCT
	Position : LREAL := 10; // in mm
	Dummy1 : LREAL := 0;
	Dummy2 : LREAL := 0;
	Dummy3 : LREAL := 0;
	Mode : MC_HomingMode := MC_DefaultHoming;
END_STRUCT
END_TYPE
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="ParametersHome">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>