<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.10">
  <POU Name="Parameter2CellDataBlock" Id="{dd1c70da-073d-4d95-8332-934c34613ac4}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Parameter2CellDataBlock : CellDataBlock
VAR_INPUT
	input : ParameterSet;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Parameter2CellDataBlock">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>